# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(600, 570)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_command = QLabel(self.centralwidget)
        self.label_command.setObjectName(u"label_command")
        self.label_command.setGeometry(QRect(100, 20, 71, 16))
        self.label_select_motor = QLabel(self.centralwidget)
        self.label_select_motor.setObjectName(u"label_select_motor")
        self.label_select_motor.setGeometry(QRect(100, 60, 91, 20))
        self.combo_motor = QComboBox(self.centralwidget)
        self.combo_motor.setObjectName(u"combo_motor")
        self.combo_motor.setGeometry(QRect(200, 60, 271, 21))
        self.label_arg1 = QLabel(self.centralwidget)
        self.label_arg1.setObjectName(u"label_arg1")
        self.label_arg1.setGeometry(QRect(100, 100, 47, 16))
        self.line_arg1 = QLineEdit(self.centralwidget)
        self.line_arg1.setObjectName(u"line_arg1")
        self.line_arg1.setGeometry(QRect(200, 100, 271, 21))
        self.label_arg2 = QLabel(self.centralwidget)
        self.label_arg2.setObjectName(u"label_arg2")
        self.label_arg2.setGeometry(QRect(100, 140, 47, 16))
        self.line_arg2 = QLineEdit(self.centralwidget)
        self.line_arg2.setObjectName(u"line_arg2")
        self.line_arg2.setGeometry(QRect(200, 140, 271, 21))
        self.button_send = QPushButton(self.centralwidget)
        self.button_send.setObjectName(u"button_send")
        self.button_send.setGeometry(QRect(250, 180, 121, 31))
        self.label_motor_info = QLabel(self.centralwidget)
        self.label_motor_info.setObjectName(u"label_motor_info")
        self.label_motor_info.setGeometry(QRect(110, 270, 71, 21))
        self.text_output = QTextEdit(self.centralwidget)
        self.text_output.setObjectName(u"text_output")
        self.text_output.setGeometry(QRect(10, 340, 581, 221))
        self.text_output.setReadOnly(True)
        self.combo_command = QComboBox(self.centralwidget)
        self.combo_command.setObjectName(u"combo_command")
        self.combo_command.setGeometry(QRect(200, 20, 271, 26))
        self.motor_pos = QLCDNumber(self.centralwidget)
        self.motor_pos.setObjectName(u"motor_pos")
        self.motor_pos.setGeometry(QRect(230, 300, 161, 23))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(86, 86, 86, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(129, 129, 129, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(107, 107, 107, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(43, 43, 43, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(57, 57, 57, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.motor_pos.setPalette(palette)
        self.motor_pos.setDigitCount(8)
        self.label_motor_info_2 = QLabel(self.centralwidget)
        self.label_motor_info_2.setObjectName(u"label_motor_info_2")
        self.label_motor_info_2.setGeometry(QRect(110, 300, 71, 21))
        self.motor_state = QTextEdit(self.centralwidget)
        self.motor_state.setObjectName(u"motor_state")
        self.motor_state.setGeometry(QRect(230, 270, 161, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 240, 61, 16))
        self.combo_axis = QComboBox(self.centralwidget)
        self.combo_axis.setObjectName(u"combo_axis")
        self.combo_axis.setGeometry(QRect(230, 240, 161, 22))
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.combo_motor, self.line_arg1)
        QWidget.setTabOrder(self.line_arg1, self.line_arg2)
        QWidget.setTabOrder(self.line_arg2, self.button_send)
        QWidget.setTabOrder(self.button_send, self.text_output)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Controller Commands", None))
        self.label_command.setText(QCoreApplication.translate("MainWindow", u"Command:", None))
        self.label_select_motor.setText(QCoreApplication.translate("MainWindow", u"Select Motor:", None))
        self.label_arg1.setText(QCoreApplication.translate("MainWindow", u"Arg1:", None))
        self.label_arg2.setText(QCoreApplication.translate("MainWindow", u"Arg2:", None))
        self.button_send.setText(QCoreApplication.translate("MainWindow", u"Send Command", None))
        self.label_motor_info.setText(QCoreApplication.translate("MainWindow", u"Motor Status ", None))
        self.text_output.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Command output will be displayed here...", None))
        self.label_motor_info_2.setText(QCoreApplication.translate("MainWindow", u"Motor Position", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Choose axis", None))
    # retranslateUi

